// Generated by dts-bundle v0.2.0

declare module 'master-control' {
    export import Leaderboards = require('master-control/controllers/LeaderboardsController');
    export import Games = require('master-control/controllers/GamesController');
}

declare module 'master-control/controllers/LeaderboardsController' {
    import Score = require('master-control/models/Score');
    module LeaderboardsController {
        module Scores {
            var PATH: string;
            interface Data {
                id: number;
            }
            interface Return {
                scores: Score[];
            }
            function handler(reply: SocketRouter.Reply<Return>, data: Data): void;
        }
    }
    export = LeaderboardsController;
}

declare module 'master-control/controllers/GamesController' {
    module GamesController {
        module List {
            var PATH: string;
            interface Data {
            }
            interface Return {
                games: any[];
            }
            function handler(reply: SocketRouter.Reply<Return>, data: Data): void;
        }
    }
    export = GamesController;
}

declare module 'master-control/models/Score' {
    interface Score {
        value: number;
        dateAchieved: Date;
    }
    export = Score;
}

